spring:
  application:
    name: terminal-service
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#  datasource:
#    diver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa


  profiles:
    include: s3, kakao, db